# NAME: Virgil Jose
# EMAIL: xxxxxxxxx
# ID: xxxxxxxxx

default: lab1a.c
	@gcc -g -Wall -Wextra -o lab1a lab1a.c

clean:
	@rm -rf lab1a *.tar.gz

dist: default
	@tar -czf lab1a-904765891.tar.gz lab1a.c Makefile README
