# NAME: Virgil Jose, Christopher Ngai
# EMAIL: xxxxxxxxx, xxxxxxxxx
# ID: xxxxxxxxx, xxxxxxxxx

CC = gcc
CFLAGS = -Wall -Wextra

default:
	$(CC) $(CFLAGS) -o lab3a lab3a.c

dist:
	tar -czf lab3a-xxxxxxxxx.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -rf lab3a lab3a-xxxxxxxxx.tar.gz