# NAME: Virgil Jose, Christopher Ngai
# EMAIL: xxxxxxxxx, xxxxxxxxx
# ID: xxxxxxxxx, xxxxxxxxx

default:
	cp lab3b.py lab3b
	chmod +x lab3b

dist:
	tar -czf lab3b-xxxxxxxxx.tar.gz lab3b.py Makefile README

clean:
	rm -f lab3b lab3b-xxxxxxxxx.tar.gz